<?php

namespace App\Filament\Actions;

use App\Engine\FlagEngine;
use App\Engine\OpenBankingEngine;
use Filament\Forms\Components\Toggle;
use Filament\Tables\Actions\BulkAction;
use Illuminate\Database\Eloquent\Collection;

class RunEngineBulkAction extends BulkAction
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->icon('');
        $this->form([
            Toggle::make('update_merchant')
                ->label('Update Merchant')
                ->default(false),
            Toggle::make('flag_engine')
                ->label('Flag engine')
                ->default(false)
        ]);
        $this->action(function (Collection $records, array $data) {
            if (isset($data['update_merchant'])) {
                foreach ($records as $record) {
                    if (!is_null($record->open_banking_transaction))
                    {
                        $data = OpenBankingEngine::parse($record->open_banking_transaction);
                        $record->merchant = $data['merchant'];
                    }
                }
            }
            if (isset($data['flag_engine'])) {
                $records = FlagEngine::run($records);
            }
            foreach ($records as $record) {
                if ($record->isDirty())
                {
                    $record->save();
                }
            }
        });
    }
}
